export const translations = {
  en: {
    common: { emptyTitle: 'Nothing here yet', emptyBody: 'This area is ready for its feature branch.', search: 'Search', seeAll: 'See all', language: 'TH' },
    role: { choose: 'Choose a workspace', preview: 'Development preview only — authentication will be added later.', student: 'Student', employer: 'Employer', admin: 'Admin', studentBody: 'Find and manage nearby opportunities.', employerBody: 'Create jobs and review applicants.', adminBody: 'Review users, jobs, and reports.' },
    tabs: { home: 'Home', explore: 'Explore', applications: 'Applications', messages: 'Messages', profile: 'Profile', dashboard: 'Overview', jobs: 'Jobs', applicants: 'Applicants', users: 'Users', reports: 'Reports' },
    student: { homeTitle: 'Find work near you', homeSubtitle: 'Opportunities for KU Sriracha students', verified: 'KU student verification', searchPlaceholder: 'Search jobs, companies, or keywords', nearby: 'Jobs near you', exploreTitle: 'Find your job', applications: 'Applications', messages: 'Messages', profile: 'Profile', filters: { all: 'All', food: 'Food & Beverage', retail: 'Retail', event: 'Event', date: 'Date', category: 'Category', area: 'Area', time: 'Time', wage: 'Wage' } },
    employer: { dashboard: 'Employer overview', dashboardSubtitle: 'Manage jobs and applicants in one place', createJob: 'Create new job', createSubtitle: 'Build the form UI here, then connect the API in its feature branch.', jobTitle: 'Job title', jobType: 'Job type', wage: 'Wage', location: 'Location', dateTime: 'Date and time', skills: 'Required skills', description: 'Job description', publish: 'Publish job', activeJobs: 'Active jobs', applications: 'Applications', accepted: 'Accepted', completed: 'Completed', recent: 'Recent applicants', jobs: 'Job listings', applicants: 'Applicants', messages: 'Messages', profile: 'Business profile' },
    admin: { dashboard: 'Platform overview', dashboardSubtitle: 'Keep JobMor safe, trusted, and growing', students: 'Students', employers: 'Employers', activeJobs: 'Active jobs', reports: 'Reports', verifications: 'Pending verifications', health: 'Platform health', recent: 'Recent reports and verifications', users: 'Users', jobs: 'Jobs', profile: 'Admin profile' },
  },
  th: {
    common: { emptyTitle: 'ยังไม่มีข้อมูล', emptyBody: 'พื้นที่นี้พร้อมสำหรับการพัฒนาต่อใน feature branch', search: 'ค้นหา', seeAll: 'ดูทั้งหมด', language: 'EN' },
    role: { choose: 'เลือกพื้นที่ทำงาน', preview: 'สำหรับดู UI ระหว่างพัฒนาเท่านั้น — ระบบเข้าสู่ระบบจะทำภายหลัง', student: 'นักศึกษา', employer: 'ผู้ประกอบการ', admin: 'ผู้ดูแลระบบ', studentBody: 'ค้นหาและจัดการโอกาสงานใกล้คุณ', employerBody: 'สร้างงานและตรวจสอบผู้สมัคร', adminBody: 'ตรวจสอบผู้ใช้ งาน และรายงาน' },
    tabs: { home: 'หน้าแรก', explore: 'ค้นหา', applications: 'ใบสมัคร', messages: 'ข้อความ', profile: 'โปรไฟล์', dashboard: 'ภาพรวม', jobs: 'งาน', applicants: 'ผู้สมัคร', users: 'ผู้ใช้', reports: 'รายงาน' },
    student: { homeTitle: 'หางานใกล้คุณ', homeSubtitle: 'โอกาสสำหรับนิสิต มก. ศรีราชา', verified: 'การยืนยันนิสิต มก.', searchPlaceholder: 'ค้นหางาน ร้านค้า หรือคำสำคัญ', nearby: 'งานใกล้คุณ', exploreTitle: 'ค้นหางานที่ใช่', applications: 'ใบสมัครของฉัน', messages: 'ข้อความ', profile: 'โปรไฟล์', filters: { all: 'ทั้งหมด', food: 'อาหารและเครื่องดื่ม', retail: 'ค้าปลีก', event: 'อีเวนต์', date: 'วันที่', category: 'หมวดหมู่', area: 'พื้นที่', time: 'เวลา', wage: 'ค่าจ้าง' } },
    employer: { dashboard: 'ภาพรวมผู้ประกอบการ', dashboardSubtitle: 'จัดการประกาศงานและผู้สมัครในที่เดียว', createJob: 'สร้างประกาศงาน', createSubtitle: 'เตรียม UI ฟอร์มไว้ แล้วเชื่อม API ใน feature branch', jobTitle: 'ชื่อตำแหน่งงาน', jobType: 'ประเภทงาน', wage: 'ค่าจ้าง', location: 'สถานที่', dateTime: 'วันและเวลา', skills: 'ทักษะที่ต้องการ', description: 'รายละเอียดงาน', publish: 'เผยแพร่งาน', activeJobs: 'งานที่เปิดรับ', applications: 'ใบสมัคร', accepted: 'รับเข้าทำงาน', completed: 'เสร็จสิ้น', recent: 'ผู้สมัครล่าสุด', jobs: 'ประกาศงาน', applicants: 'ผู้สมัคร', messages: 'ข้อความ', profile: 'โปรไฟล์ธุรกิจ' },
    admin: { dashboard: 'ภาพรวมแพลตฟอร์ม', dashboardSubtitle: 'ดูแล JobMor ให้ปลอดภัย น่าเชื่อถือ และเติบโต', students: 'นิสิต', employers: 'ผู้ประกอบการ', activeJobs: 'งานที่เปิดรับ', reports: 'รายงาน', verifications: 'รอตรวจสอบ', health: 'สถานะระบบ', recent: 'รายงานและคำขอตรวจสอบล่าสุด', users: 'ผู้ใช้', jobs: 'งาน', profile: 'โปรไฟล์ผู้ดูแล' },
  },
} as const;

export type AppLanguage = keyof typeof translations;
