import type {
  VerificationQueueItem,
  ReportQueueItem,
  ManagedUserItem,
  DetailedReportItem,
  ModeratedJobItem,
  AdminAuditLogItem,
} from '../types/moderation';

export const MOCK_VERIFICATIONS: VerificationQueueItem[] = [
  {
    id: 'ver-01',
    studentName: 'สมชาย ใจดี',
    studentId: '653020012-3',
    faculty: 'วิศวกรรมศาสตร์ ศรีราชา',
    universityEmail: 'somchai.ja@ku.th',
    submittedAt: '2026-09-21T10:30:00Z',
    status: 'pending',
  },
  {
    id: 'ver-02',
    studentName: 'กนกวรรณ สุขเสริฐ',
    studentId: '643030114-1',
    faculty: 'วิทยาการจัดการ',
    universityEmail: 'kanokwan.su@ku.th',
    submittedAt: '2026-09-21T09:15:00Z',
    status: 'pending',
  },
  {
    id: 'ver-03',
    studentName: 'ธนกฤต วิเศษศิลป์',
    studentId: '663010450-8',
    faculty: 'พาณิชยนาวีนานาชาติ',
    universityEmail: 'thanakrit.v@ku.th',
    submittedAt: '2026-09-20T16:45:00Z',
    status: 'pending',
  },
];

export const MOCK_REPORTS: ReportQueueItem[] = [
  {
    id: 'rep-01',
    reporterName: 'ร้านกาแฟ KU Corner',
    targetType: 'user',
    targetName: 'นิสิตทดลองงาน A',
    reason: 'ไม่มาทำงานตามนัดหมายโดยไม่แจ้งล่วงหน้า',
    createdAt: '2026-09-21T14:20:00Z',
    status: 'pending',
  },
  {
    id: 'rep-02',
    reporterName: 'นิสิต มก. ศรีราชา',
    targetType: 'job',
    targetName: 'พนักงานแจกใบโบร์ชัวร์รายวัน',
    reason: 'รายละเอียดค่าจ้างไม่ตรงตามที่ประกาศไว้',
    createdAt: '2026-09-20T11:00:00Z',
    status: 'pending',
  },
];

export const MOCK_DETAILED_REPORTS: DetailedReportItem[] = [
  {
    id: 'rep-01',
    reporterName: 'นิสิต มก. นิรนาม',
    reporterRole: 'student',
    targetType: 'job',
    targetName: 'งานคีย์ข้อมูล WFH รายได้วันละ 1,500 บาท',
    targetDetails: 'ผู้ว่าจ้าง: บริษัท ดิจิทัลโปร โมบาย จำกัด',
    category: 'fraud',
    reason: 'มีการเรียกเก็บค่ามัดจำอุปกรณ์ก่อนเริ่มงาน เข้าข่ายหลอกลวง',
    severity: 'high',
    createdAt: '2026-09-21T15:10:00Z',
    status: 'pending',
  },
  {
    id: 'rep-02',
    reporterName: 'ร้านกาแฟ KU Corner',
    reporterRole: 'employer',
    targetType: 'user',
    targetName: 'สมหมาย แสนสุข (นิสิตชั้นปีที่ 2)',
    targetDetails: 'รหัส: 653020088-1 • วิศวกรรมศาสตร์',
    category: 'no_show',
    reason: 'ยืนยันกะทำงานแล้วไม่มาปฏิบัติงานโดยไม่แจ้งล่วงหน้า ติดต่อไม่ได้',
    severity: 'medium',
    createdAt: '2026-09-21T14:20:00Z',
    status: 'pending',
  },
  {
    id: 'rep-03',
    reporterName: 'นิสิต มก. ศรีราชา',
    reporterRole: 'student',
    targetType: 'job',
    targetName: 'พนักงานแจกใบโบร์ชัวร์รายวัน ประตู 1',
    targetDetails: 'ผู้ว่าจ้าง: เอเจนซี่อีเวนต์ พัทยา',
    category: 'wage_dispute',
    reason: 'ประกาศระบุค่าจ้างวันละ 500 บาท แต่จ่ายจริงเพียง 350 บาท',
    severity: 'medium',
    createdAt: '2026-09-20T11:00:00Z',
    status: 'pending',
  },
  {
    id: 'rep-04',
    reporterName: 'ผู้ประกอบการ ย่านอ่าวอุดม',
    reporterRole: 'employer',
    targetType: 'user',
    targetName: 'ผู้สมัครไม่ระบุตัวตน',
    targetDetails: 'อีเมล: user994@gmail.com',
    category: 'inappropriate',
    reason: 'ส่งข้อความและรูปภาพที่ไม่เหมาะสมเข้ามาในช่องแชทประกาศงาน',
    severity: 'low',
    createdAt: '2026-09-19T18:30:00Z',
    status: 'pending',
  },
  {
    id: 'rep-05',
    reporterName: 'แอดมินระบบอัตโนมัติ',
    reporterRole: 'anonymous',
    targetType: 'job',
    targetName: 'ผู้ช่วยเสิร์ฟร้านชาบู',
    targetDetails: 'ผู้ว่าจ้าง: ชาบูอินดี้ อ่าวอุดม',
    category: 'other',
    reason: 'ระบุตำแหน่งแผนที่ไม่ถูกต้อง (นอกเขตศรีราชา)',
    severity: 'low',
    createdAt: '2026-09-18T09:00:00Z',
    status: 'resolved',
    actionTaken: 'ปรับปรุงพิกัดแผนที่ให้ถูกต้องเรียบร้อยแล้ว',
  },
];

export const MOCK_MANAGED_USERS: ManagedUserItem[] = [
  {
    id: 'usr-01',
    displayName: 'สมชาย ใจดี',
    email: 'somchai.ja@ku.th',
    role: 'student',
    accountStatus: 'pending',
    verificationStatus: 'pending',
    studentId: '653020012-3',
    faculty: 'วิศวกรรมศาสตร์ ศรีราชา',
    universityEmail: 'somchai.ja@ku.th',
    joinedAt: '2026-09-21',
  },
  {
    id: 'usr-02',
    displayName: 'กนกวรรณ สุขเสริฐ',
    email: 'kanokwan.su@ku.th',
    role: 'student',
    accountStatus: 'pending',
    verificationStatus: 'pending',
    studentId: '643030114-1',
    faculty: 'วิทยาการจัดการ',
    universityEmail: 'kanokwan.su@ku.th',
    joinedAt: '2026-09-21',
  },
  {
    id: 'usr-03',
    displayName: 'อภิสิทธิ์ วงศ์สวรรค์',
    email: 'apisit.w@ku.th',
    role: 'student',
    accountStatus: 'active',
    verificationStatus: 'verified',
    studentId: '633010022-9',
    faculty: 'วิทยาศาสตร์ ศรีราชา',
    universityEmail: 'apisit.w@ku.th',
    joinedAt: '2026-08-15',
  },
  {
    id: 'usr-04',
    displayName: 'Café Amazon KU Branch',
    email: 'contact@cafeamazon-ku.com',
    role: 'employer',
    accountStatus: 'active',
    companyName: 'Café Amazon สาขา มก. ศรีราชา',
    category: 'อาหารและเครื่องดื่ม',
    joinedAt: '2026-07-10',
  },
  {
    id: 'usr-05',
    displayName: 'Seven-Eleven อ่าวอุดม',
    email: 'hr@7eleven-aoudom.co.th',
    role: 'employer',
    accountStatus: 'active',
    companyName: '7-Eleven สาขาประตู 1 อ่าวอุดม',
    category: 'ค้าปลีกและบริการ',
    joinedAt: '2026-06-01',
  },
  {
    id: 'usr-06',
    displayName: 'พงศกร สันติสุข',
    email: 'pongsakorn.s@gmail.com',
    role: 'student',
    accountStatus: 'suspended',
    verificationStatus: 'rejected',
    studentId: '623050119-0',
    faculty: 'เศรษฐศาสตร์ ศรีราชา',
    joinedAt: '2026-05-18',
  },
];

export const MOCK_MODERATED_JOBS: ModeratedJobItem[] = [
  {
    id: 'job-01',
    title: 'พนักงานบาริสต้า พาร์ทไทม์ ช่วงเย็น',
    companyName: 'Café Amazon สาขา มก. ศรีราชา',
    employerId: 'usr-04',
    wage: '65 บาท/ชม.',
    location: 'ภายในวิทยาเขต มก. ศรีราชา',
    category: 'อาหารและเครื่องดื่ม',
    jobType: 'Part-time',
    description: 'ชงกาแฟ ดูแลเคาน์เตอร์ และบริการลูกค้า วันจันทร์-ศุกร์ เวลา 16:30 - 20:30 น.',
    postedAt: '2026-09-21',
    moderationStatus: 'active',
  },
  {
    id: 'job-02',
    title: 'พนักงานจัดเรียงสินค้า กะวันหยุด',
    companyName: '7-Eleven สาขาประตู 1 อ่าวอุดม',
    employerId: 'usr-05',
    wage: '450 บาท/วัน',
    location: 'หน้าประตู 1 มก. ศรีราชา',
    category: 'ค้าปลีกและบริการ',
    jobType: 'รายวัน',
    description: 'จัดเรียงสินค้าหน้าร้าน ตรวจเช็คสต็อกสินค้า เสาร์-อาทิตย์',
    postedAt: '2026-09-20',
    moderationStatus: 'active',
  },
  {
    id: 'job-03',
    title: 'งานคีย์ข้อมูล WFH รายได้วันละ 1,500 บาท',
    companyName: 'บริษัท ดิจิทัลโปร โมบาย จำกัด',
    employerId: 'usr-99',
    wage: '1,500 บาท/วัน',
    location: 'Work From Home',
    category: 'งานออนไลน์',
    jobType: 'รายวัน',
    description: 'พิมพ์เอกสารง่ายๆ รับงานผ่านไลน์ รายได้การันตีวันละ 1,500 บาท',
    postedAt: '2026-09-21',
    moderationStatus: 'flagged',
    flagCount: 4,
    flagReason: 'มีการขอเก็บค่ามัดจำโปรแกรมก่อนเริ่มงาน เข้าข่ายหลอกลวง',
  },
  {
    id: 'job-04',
    title: 'พนักงานแจกใบโบร์ชัวร์รายวัน ประตู 1',
    companyName: 'เอเจนซี่อีเวนต์ พัทยา',
    employerId: 'usr-98',
    wage: '500 บาท/วัน',
    location: 'ทางเข้าประตู 1 มก. ศรีราชา',
    category: 'อีเวนต์และการตลาด',
    jobType: 'รายวัน',
    description: 'แจกใบปลิวประชาสัมพันธ์คอนโดมิเนียม เวลา 10:00 - 16:00 น.',
    postedAt: '2026-09-19',
    moderationStatus: 'flagged',
    flagCount: 2,
    flagReason: 'นิสิตแจ้งว่าจ่ายค่าจ้างจริงไม่ตรงกับที่ระบุในประกาศ',
  },
  {
    id: 'job-05',
    title: 'แอดมินตอบแชทเว็บเกมออนไลน์ 24 ชม.',
    companyName: 'Lucky Games Studio',
    employerId: 'usr-97',
    wage: '2,000 บาท/วัน',
    location: 'ออนไลน์',
    category: 'งานออนไลน์',
    jobType: 'รายวัน',
    description: 'ตอบคำถามลูกค้าเกี่ยวกับการฝาก-ถอน',
    postedAt: '2026-09-15',
    moderationStatus: 'taken_down',
    takedownReason: 'ละเมิดนโยบายความปลอดภัย (โฆษณาเว็บพนันออนไลน์)',
  },
];

export const MOCK_AUDIT_LOGS: AdminAuditLogItem[] = [
  {
    id: 'log-01',
    action: 'อนุมัติยืนยันสิทธิ์นิสิต มก.',
    target: 'สมชาย ใจดี (653020012-3)',
    adminName: 'Admin KU-01',
    timestamp: '2026-09-21 21:30',
    type: 'verify',
  },
  {
    id: 'log-02',
    action: 'ระงับประกาศงานหลอกลวง (WFH)',
    target: 'บริษัท ดิจิทัลโปร โมบาย จำกัด',
    adminName: 'Admin KU-01',
    timestamp: '2026-09-21 19:45',
    type: 'job',
  },
  {
    id: 'log-03',
    action: 'ดำเนินการเคสข้อร้องเรียน',
    target: 'รายงานข้อพิพาทค่าจ้าง แจกใบปลิว',
    adminName: 'Admin KU-02',
    timestamp: '2026-09-20 14:15',
    type: 'report',
  },
  {
    id: 'log-04',
    action: 'ระงับบัญชีผู้ใช้งานที่ละเมิดกฎ',
    target: 'พงศกร สันติสุข (623050119-0)',
    adminName: 'Admin KU-01',
    timestamp: '2026-09-19 11:20',
    type: 'user',
  },
  {
    id: 'log-05',
    action: 'ตรวจสอบระบบความปลอดภัย RLS',
    target: 'Supabase Authorization Policies',
    adminName: 'System Engine',
    timestamp: '2026-09-18 08:00',
    type: 'system',
  },
];
