import type { VerificationQueueItem, ReportQueueItem, ManagedUserItem, DetailedReportItem } from '../types/moderation';

export const MOCK_VERIFICATIONS: VerificationQueueItem[] = [
  {
    id: 'ver-01',
    studentName: 'สมชาย ใจดี',
    studentId: '653020012-3',
    faculty: 'วิศวกรรมศาสตร์ ศรีราชา',
    universityEmail: 'somchai.ja@ku.th',
    submittedAt: '2026-09-21T10:30:00Z',
    status: 'pending',
  },
  {
    id: 'ver-02',
    studentName: 'กนกวรรณ สุขเสริฐ',
    studentId: '643030114-1',
    faculty: 'วิทยาการจัดการ',
    universityEmail: 'kanokwan.su@ku.th',
    submittedAt: '2026-09-21T09:15:00Z',
    status: 'pending',
  },
  {
    id: 'ver-03',
    studentName: 'ธนกฤต วิเศษศิลป์',
    studentId: '663010450-8',
    faculty: 'พาณิชยนาวีนานาชาติ',
    universityEmail: 'thanakrit.v@ku.th',
    submittedAt: '2026-09-20T16:45:00Z',
    status: 'pending',
  },
];

export const MOCK_REPORTS: ReportQueueItem[] = [
  {
    id: 'rep-01',
    reporterName: 'ร้านกาแฟ KU Corner',
    targetType: 'user',
    targetName: 'นิสิตทดลองงาน A',
    reason: 'ไม่มาทำงานตามนัดหมายโดยไม่แจ้งล่วงหน้า',
    createdAt: '2026-09-21T14:20:00Z',
    status: 'pending',
  },
  {
    id: 'rep-02',
    reporterName: 'นิสิต มก. ศรีราชา',
    targetType: 'job',
    targetName: 'พนักงานแจกใบโบร์ชัวร์รายวัน',
    reason: 'รายละเอียดค่าจ้างไม่ตรงตามที่ประกาศไว้',
    createdAt: '2026-09-20T11:00:00Z',
    status: 'pending',
  },
];

export const MOCK_DETAILED_REPORTS: DetailedReportItem[] = [
  {
    id: 'rep-01',
    reporterName: 'นิสิต มก. นิรนาม',
    reporterRole: 'student',
    targetType: 'job',
    targetName: 'งานคีย์ข้อมูล WFH รายได้วันละ 1,500 บาท',
    targetDetails: 'ผู้ว่าจ้าง: บริษัท ดิจิทัลโปร โมบาย จำกัด',
    category: 'fraud',
    reason: 'มีการเรียกเก็บค่ามัดจำอุปกรณ์ก่อนเริ่มงาน เข้าข่ายหลอกลวง',
    severity: 'high',
    createdAt: '2026-09-21T15:10:00Z',
    status: 'pending',
  },
  {
    id: 'rep-02',
    reporterName: 'ร้านกาแฟ KU Corner',
    reporterRole: 'employer',
    targetType: 'user',
    targetName: 'สมหมาย แสนสุข (นิสิตชั้นปีที่ 2)',
    targetDetails: 'รหัส: 653020088-1 • วิศวกรรมศาสตร์',
    category: 'no_show',
    reason: 'ยืนยันกะทำงานแล้วไม่มาปฏิบัติงานโดยไม่แจ้งล่วงหน้า ติดต่อไม่ได้',
    severity: 'medium',
    createdAt: '2026-09-21T14:20:00Z',
    status: 'pending',
  },
  {
    id: 'rep-03',
    reporterName: 'นิสิต มก. ศรีราชา',
    reporterRole: 'student',
    targetType: 'job',
    targetName: 'พนักงานแจกใบโบร์ชัวร์รายวัน ประตู 1',
    targetDetails: 'ผู้ว่าจ้าง: เอเจนซี่อีเวนต์ พัทยา',
    category: 'wage_dispute',
    reason: 'ประกาศระบุค่าจ้างวันละ 500 บาท แต่จ่ายจริงเพียง 350 บาท',
    severity: 'medium',
    createdAt: '2026-09-20T11:00:00Z',
    status: 'pending',
  },
  {
    id: 'rep-04',
    reporterName: 'ผู้ประกอบการ ย่านอ่าวอุดม',
    reporterRole: 'employer',
    targetType: 'user',
    targetName: 'ผู้สมัครไม่ระบุตัวตน',
    targetDetails: 'อีเมล: user994@gmail.com',
    category: 'inappropriate',
    reason: 'ส่งข้อความและรูปภาพที่ไม่เหมาะสมเข้ามาในช่องแชทประกาศงาน',
    severity: 'low',
    createdAt: '2026-09-19T18:30:00Z',
    status: 'pending',
  },
  {
    id: 'rep-05',
    reporterName: 'แอดมินระบบอัตโนมัติ',
    reporterRole: 'anonymous',
    targetType: 'job',
    targetName: 'ผู้ช่วยเสิร์ฟร้านชาบู',
    targetDetails: 'ผู้ว่าจ้าง: ชาบูอินดี้ อ่าวอุดม',
    category: 'other',
    reason: 'ระบุตำแหน่งแผนที่ไม่ถูกต้อง (นอกเขตศรีราชา)',
    severity: 'low',
    createdAt: '2026-09-18T09:00:00Z',
    status: 'resolved',
    actionTaken: 'ปรับปรุงพิกัดแผนที่ให้ถูกต้องเรียบร้อยแล้ว',
  },
];

export const MOCK_MANAGED_USERS: ManagedUserItem[] = [
  {
    id: 'usr-01',
    displayName: 'สมชาย ใจดี',
    email: 'somchai.ja@ku.th',
    role: 'student',
    accountStatus: 'pending',
    verificationStatus: 'pending',
    studentId: '653020012-3',
    faculty: 'วิศวกรรมศาสตร์ ศรีราชา',
    universityEmail: 'somchai.ja@ku.th',
    joinedAt: '2026-09-21',
  },
  {
    id: 'usr-02',
    displayName: 'กนกวรรณ สุขเสริฐ',
    email: 'kanokwan.su@ku.th',
    role: 'student',
    accountStatus: 'pending',
    verificationStatus: 'pending',
    studentId: '643030114-1',
    faculty: 'วิทยาการจัดการ',
    universityEmail: 'kanokwan.su@ku.th',
    joinedAt: '2026-09-21',
  },
  {
    id: 'usr-03',
    displayName: 'อภิสิทธิ์ วงศ์สวรรค์',
    email: 'apisit.w@ku.th',
    role: 'student',
    accountStatus: 'active',
    verificationStatus: 'verified',
    studentId: '633010022-9',
    faculty: 'วิทยาศาสตร์ ศรีราชา',
    universityEmail: 'apisit.w@ku.th',
    joinedAt: '2026-08-15',
  },
  {
    id: 'usr-04',
    displayName: 'Café Amazon KU Branch',
    email: 'contact@cafeamazon-ku.com',
    role: 'employer',
    accountStatus: 'active',
    companyName: 'Café Amazon สาขา มก. ศรีราชา',
    category: 'อาหารและเครื่องดื่ม',
    joinedAt: '2026-07-10',
  },
  {
    id: 'usr-05',
    displayName: 'Seven-Eleven อ่าวอุดม',
    email: 'hr@7eleven-aoudom.co.th',
    role: 'employer',
    accountStatus: 'active',
    companyName: '7-Eleven สาขาประตู 1 อ่าวอุดม',
    category: 'ค้าปลีกและบริการ',
    joinedAt: '2026-06-01',
  },
  {
    id: 'usr-06',
    displayName: 'พงศกร สันติสุข',
    email: 'pongsakorn.s@gmail.com',
    role: 'student',
    accountStatus: 'suspended',
    verificationStatus: 'rejected',
    studentId: '623050119-0',
    faculty: 'เศรษฐศาสตร์ ศรีราชา',
    joinedAt: '2026-05-18',
  },
];
