export const studentCopy = {
  en: {
    availableJobs: 'Available jobs', results: 'Matching jobs', filters: 'Filters', searchHint: 'Find work that fits your schedule',
    profileTooLong: 'Use up to 160 characters for your name and 20 for your phone.',
    savedJobs: 'Saved jobs', saveJob: 'Save job', unsave: 'Unsave job', saved: 'Saved', notApplied: 'Not applied',
    apply: 'Apply for job', applied: 'Application submitted.', withdraw: 'Withdraw application', withdrawn: 'Application withdrawn.',
    withdrawTitle: 'Withdraw this application?', withdrawBody: 'Your pending application will be removed. You can apply again while the job is active.',
    duplicate: 'You have already applied for this job. Refresh to see its current status.',
    cannotWithdraw: 'This application is no longer pending or is unavailable. Refresh to see its current status.',
    verifiedRequired: 'A verified, active student account is required.', signInRequired: 'Please sign in with a student account.',
    error: 'Could not complete this request. Check your connection and try again.', jobNotFound: 'This job is unavailable or you do not have access.',
    emptyJobs: 'No matching jobs', emptyJobsBody: 'Try another search or check back for new opportunities.',
    emptySaved: 'No saved jobs', emptySavedBody: 'Save a job from the list or its details to find it here.',
    emptyApplications: 'No applications yet', emptyApplicationsBody: 'Your applications and their current status will appear here.',
    required: 'Name and phone must not be blank.', profileSaved: 'Profile updated.',
    search: 'Search jobs, descriptions, or locations', minimumWage: 'Minimum wage (THB, any pay unit)',
    clearFilters: 'Clear filters', unavailable: 'Job no longer available',
  },
  th: {
    availableJobs: 'งานที่เปิดรับสมัคร', results: 'งานที่ตรงกับการค้นหา', filters: 'ตัวกรอง', searchHint: 'ค้นหางานที่เข้ากับตารางเรียนของคุณ',
    profileTooLong: 'ชื่อยาวได้ไม่เกิน 160 ตัวอักษร และเบอร์โทรไม่เกิน 20 ตัวอักษร',
    savedJobs: 'งานที่บันทึกไว้', saveJob: 'บันทึกงาน', unsave: 'เลิกบันทึกงาน', saved: 'บันทึกแล้ว', notApplied: 'ยังไม่ได้สมัคร',
    apply: 'สมัครงาน', applied: 'ส่งใบสมัครแล้ว', withdraw: 'ถอนใบสมัคร', withdrawn: 'ถอนใบสมัครแล้ว',
    withdrawTitle: 'ถอนใบสมัครนี้?', withdrawBody: 'ใบสมัครที่รอพิจารณาจะถูกลบ คุณสมัครใหม่ได้หากงานยังเปิดรับอยู่',
    duplicate: 'คุณสมัครงานนี้แล้ว กรุณารีเฟรชเพื่อดูสถานะล่าสุด',
    cannotWithdraw: 'ใบสมัครนี้ไม่ได้อยู่ระหว่างรอพิจารณาหรือไม่พบใบสมัคร กรุณารีเฟรชเพื่อดูสถานะล่าสุด',
    verifiedRequired: 'ต้องใช้บัญชีนิสิตที่ยืนยันแล้วและไม่ถูกระงับ', signInRequired: 'กรุณาเข้าสู่ระบบด้วยบัญชีนิสิต',
    error: 'ดำเนินการไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อและลองอีกครั้ง', jobNotFound: 'งานนี้ไม่พร้อมใช้งานหรือคุณไม่มีสิทธิ์เข้าถึง',
    emptyJobs: 'ไม่พบงานที่ตรงกับการค้นหา', emptyJobsBody: 'ลองเปลี่ยนคำค้นหาหรือกลับมาตรวจสอบงานใหม่',
    emptySaved: 'ยังไม่มีงานที่บันทึกไว้', emptySavedBody: 'บันทึกงานจากรายการหรือหน้ารายละเอียดเพื่อกลับมาดูที่นี่',
    emptyApplications: 'ยังไม่มีใบสมัคร', emptyApplicationsBody: 'ใบสมัครและสถานะล่าสุดของคุณจะแสดงที่นี่',
    required: 'กรุณากรอกชื่อและเบอร์โทรศัพท์', profileSaved: 'บันทึกโปรไฟล์แล้ว',
    search: 'ค้นหาชื่องาน รายละเอียด หรือสถานที่', minimumWage: 'ค่าจ้างขั้นต่ำ (บาท รวมทุกหน่วยค่าจ้าง)',
    clearFilters: 'ล้างตัวกรอง', unavailable: 'งานนี้ไม่พร้อมใช้งานแล้ว',
  },
};
