-- JobMor authentication and profile foundation.
-- Public registration accepts only student and employer roles.
-- Admin creation is a one-time server-side operation; never expose service_role to the app.

create type public.app_role as enum ('student', 'employer', 'admin');
create type public.verification_status as enum ('pending_email', 'verified', 'suspended');

create table public.business_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_en text not null,
  name_th text not null,
  created_at timestamptz not null default now()
);

insert into public.business_categories (slug, name_en, name_th)
values
  ('food-beverage', 'Food & Beverage', 'อาหารและเครื่องดื่ม'),
  ('retail', 'Retail', 'ค้าปลีก'),
  ('hospitality', 'Hospitality', 'โรงแรมและที่พัก'),
  ('education', 'Education', 'การศึกษา'),
  ('events', 'Events', 'อีเวนต์'),
  ('office', 'Office & Administration', 'สำนักงานและธุรการ'),
  ('technology', 'Technology', 'เทคโนโลยี'),
  ('logistics', 'Logistics', 'ขนส่งและโลจิสติกส์');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.app_role not null,
  email text not null unique,
  display_name text not null check (length(trim(display_name)) > 0),
  phone text not null check (length(trim(phone)) > 0),
  verification_status public.verification_status not null default 'pending_email',
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_email_must_be_ku
    check (role <> 'student' or email ~* '^[A-Z0-9._%+\-]+@ku\.th$')
);

-- A partial unique index enforces the requirement that JobMor has only one admin.
create unique index profiles_single_admin_idx
  on public.profiles ((role))
  where role = 'admin';

create table public.employer_profiles (
  id uuid primary key references public.profiles (id) on delete cascade,
  company_name text not null check (length(trim(company_name)) > 0),
  business_category text not null check (length(trim(business_category)) > 0),
  address text not null check (length(trim(address)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger employer_profiles_set_updated_at
  before update on public.employer_profiles
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role text := new.raw_user_meta_data ->> 'role';
  user_name text := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');
  user_phone text := nullif(trim(new.raw_user_meta_data ->> 'phone'), '');
  company text := nullif(trim(new.raw_user_meta_data ->> 'company_name'), '');
  category text := nullif(trim(new.raw_user_meta_data ->> 'business_category'), '');
  company_address text := nullif(trim(new.raw_user_meta_data ->> 'address'), '');
begin
  if requested_role not in ('student', 'employer') then
    raise exception 'Public registration accepts only student or employer roles';
  end if;

  if user_name is null or user_phone is null then
    raise exception 'display_name and phone are required';
  end if;

  if requested_role = 'student' and lower(new.email) !~ '^[a-z0-9._%+\-]+@ku\.th$' then
    raise exception 'Student registration requires a ku.th email address';
  end if;

  if requested_role = 'employer' and
     (company is null or category is null or company_address is null) then
    raise exception 'Employer company name, business category, and address are required';
  end if;

  insert into public.profiles (id, role, email, display_name, phone)
  values (
    new.id,
    requested_role::public.app_role,
    lower(new.email),
    user_name,
    user_phone
  );

  if requested_role = 'employer' then
    insert into public.employer_profiles (
      id,
      company_name,
      business_category,
      address
    ) values (
      new.id,
      company,
      category,
      company_address
    );
  end if;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_email_verified()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.email_confirmed_at is null and new.email_confirmed_at is not null then
    update public.profiles
      set verification_status = 'verified',
          verified_at = coalesce(verified_at, now())
      where id = new.id
        and verification_status = 'pending_email';
  end if;

  return new;
end;
$$;

create trigger on_auth_user_email_verified
  after update of email_confirmed_at on auth.users
  for each row execute function public.handle_email_verified();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
      and verification_status = 'verified'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.business_categories enable row level security;
alter table public.profiles enable row level security;
alter table public.employer_profiles enable row level security;

revoke all on table public.business_categories from anon, authenticated;
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.employer_profiles from anon, authenticated;

grant select on table public.business_categories to anon, authenticated;
grant select on table public.profiles to authenticated;
grant update (display_name, phone) on table public.profiles to authenticated;
grant select on table public.employer_profiles to authenticated;
grant update (company_name, business_category, address) on table public.employer_profiles to authenticated;

create policy "Business categories are readable"
  on public.business_categories
  for select
  to anon, authenticated
  using (true);

create policy "Users can read their own profile"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Admins can read all profiles"
  on public.profiles
  for select
  to authenticated
  using ((select public.is_admin()));

create policy "Users can update their own safe profile fields"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Employers can read their own business profile"
  on public.employer_profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Admins can read all business profiles"
  on public.employer_profiles
  for select
  to authenticated
  using ((select public.is_admin()));

create policy "Employers can update their own business profile"
  on public.employer_profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

grant all on table public.business_categories to service_role;
grant all on table public.profiles to service_role;
grant all on table public.employer_profiles to service_role;
grant usage, select on sequence public.business_categories_id_seq to service_role;
