export const employerCopy = {
  en: {
    jobs: 'My jobs', create: 'Create job', edit: 'Edit job', view: 'View job', delete: 'Delete job',
    applicants: 'View applicants', profile: 'Business profile', editProfile: 'Edit profile',
    save: 'Save', cancel: 'Cancel', back: 'Back', retry: 'Try again', refresh: 'Refresh',
    loading: 'Loading…', saving: 'Saving…', saved: 'Saved successfully.', deleted: 'Job deleted.',
    deleteTitle: 'Delete this job?', deleteBody: 'Are you sure you want to delete this job? All its applications will also be deleted. This cannot be undone.',
    emptyJobs: 'No jobs yet', emptyJobsBody: 'Create your first job to start receiving applications.',
    emptyApplications: 'No applicants in this filter', emptyApplicationsBody: 'Applications for this job will appear here.',
    chooseJob: 'Choose a job to review its applicants.', all: 'All', pending: 'Pending', accepted: 'Accepted', rejected: 'Rejected',
    active: 'Active', closed: 'Closed', draft: 'Draft', hour: 'Hour', day: 'Day', month: 'Month', job: 'Job',
    title: 'Job title', description: 'Description', requirements: 'Requirements (optional)', wage: 'Wage (THB)',
    wage_type: 'Wage type', location: 'Location', category: 'Job category', working_date: 'Working date (YYYY-MM-DD)',
    shift: 'Working time / shift', workers_required: 'Workers required', contact_information: 'Contact information', status: 'Status',
    required: 'Complete all required fields within their length limits.', invalidWage: 'Enter a positive wage with up to 2 decimal places.',
    invalidWorkers: 'Enter a whole number of workers between 1 and 10,000.', invalidDate: 'Enter a valid date in YYYY-MM-DD format.',
    invalidPhone: 'Enter a valid phone number (8–20 characters).', signInRequired: 'Please sign in again.',
    verifiedRequired: 'A verified, active employer account is required.', jobNotFound: 'Job not found or access denied.',
    applicationNotFound: 'Application not found or access denied.', error: 'Could not complete this request. Check your connection and try again.',
    company: 'Company name', contact_name: 'Contact name', contact_phone: 'Phone', company_address: 'Business address', businessCategory: 'Business category',
    email: 'Email', verification: 'Verification status', verified: 'Verified', pending_email: 'Email not verified', suspended: 'Suspended',
    applicant: 'Applicant', application: 'Application details', applied: 'Applied on', message: 'Application message',
    accept: 'Accept', reject: 'Reject', updated: 'Application status updated.', unavailable: 'Not provided',
    count: 'Applicants', overview: 'Employer overview', activeJobs: 'Active jobs', totalJobs: 'Total jobs',
    formHint: 'All fields are required except requirements. Date and shift use the workplace’s local time.',
  },
  th: {
    jobs: 'งานของฉัน', create: 'สร้างประกาศงาน', edit: 'แก้ไขงาน', view: 'ดูรายละเอียด', delete: 'ลบงาน',
    applicants: 'ดูผู้สมัคร', profile: 'ข้อมูลบริษัท', editProfile: 'แก้ไขโปรไฟล์',
    save: 'บันทึก', cancel: 'ยกเลิก', back: 'ย้อนกลับ', retry: 'ลองอีกครั้ง', refresh: 'รีเฟรช',
    loading: 'กำลังโหลด…', saving: 'กำลังบันทึก…', saved: 'บันทึกสำเร็จ', deleted: 'ลบงานแล้ว',
    deleteTitle: 'ลบประกาศงานนี้?', deleteBody: 'ต้องการลบงานนี้หรือไม่? ใบสมัครทั้งหมดของงานนี้จะถูกลบด้วย และไม่สามารถกู้คืนได้',
    emptyJobs: 'ยังไม่มีประกาศงาน', emptyJobsBody: 'สร้างประกาศงานแรกเพื่อเริ่มรับสมัคร',
    emptyApplications: 'ไม่มีผู้สมัครในตัวกรองนี้', emptyApplicationsBody: 'ใบสมัครของงานนี้จะแสดงที่นี่',
    chooseJob: 'เลือกงานเพื่อดูและจัดการผู้สมัคร', all: 'ทั้งหมด', pending: 'รอพิจารณา', accepted: 'รับเข้าทำงาน', rejected: 'ปฏิเสธ',
    active: 'เปิดรับสมัคร', closed: 'ปิดรับสมัคร', draft: 'ฉบับร่าง', hour: 'ชั่วโมง', day: 'วัน', month: 'เดือน', job: 'งาน',
    title: 'ชื่องาน', description: 'รายละเอียดงาน', requirements: 'คุณสมบัติ (ไม่บังคับ)', wage: 'ค่าจ้าง (บาท)',
    wage_type: 'หน่วยค่าจ้าง', location: 'สถานที่ทำงาน', category: 'ประเภทงาน', working_date: 'วันที่ทำงาน (YYYY-MM-DD)',
    shift: 'เวลาทำงาน / กะ', workers_required: 'จำนวนที่รับ', contact_information: 'ช่องทางติดต่อ', status: 'สถานะ',
    required: 'กรุณากรอกข้อมูลที่จำเป็นให้ครบและไม่เกินจำนวนตัวอักษรที่กำหนด', invalidWage: 'กรอกค่าจ้างมากกว่า 0 และทศนิยมไม่เกิน 2 ตำแหน่ง',
    invalidWorkers: 'กรอกจำนวนเต็มตั้งแต่ 1 ถึง 10,000 คน', invalidDate: 'กรอกวันที่ที่ถูกต้องในรูปแบบ YYYY-MM-DD',
    invalidPhone: 'กรอกเบอร์โทรศัพท์ที่ถูกต้อง (8–20 ตัวอักษร)', signInRequired: 'กรุณาเข้าสู่ระบบอีกครั้ง',
    verifiedRequired: 'ต้องใช้บัญชีนายจ้างที่ยืนยันแล้วและไม่ถูกระงับ', jobNotFound: 'ไม่พบงานหรือไม่มีสิทธิ์เข้าถึง',
    applicationNotFound: 'ไม่พบใบสมัครหรือไม่มีสิทธิ์เข้าถึง', error: 'ดำเนินการไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อและลองอีกครั้ง',
    company: 'ชื่อบริษัท / ร้าน', contact_name: 'ชื่อผู้ติดต่อ', contact_phone: 'เบอร์โทรศัพท์', company_address: 'ที่อยู่บริษัท', businessCategory: 'ประเภทธุรกิจ',
    email: 'อีเมล', verification: 'สถานะการยืนยัน', verified: 'ยืนยันแล้ว', pending_email: 'ยังไม่ยืนยันอีเมล', suspended: 'ถูกระงับ',
    applicant: 'ผู้สมัคร', application: 'รายละเอียดใบสมัคร', applied: 'วันที่สมัคร', message: 'ข้อความจากผู้สมัคร',
    accept: 'รับเข้าทำงาน', reject: 'ปฏิเสธ', updated: 'อัปเดตสถานะใบสมัครแล้ว', unavailable: 'ไม่ได้ระบุ',
    count: 'ผู้สมัคร', overview: 'ภาพรวมนายจ้าง', activeJobs: 'งานที่เปิดรับ', totalJobs: 'งานทั้งหมด',
    formHint: 'กรอกทุกช่องยกเว้นคุณสมบัติ วันที่และกะใช้เวลาท้องถิ่นของสถานที่ทำงาน',
  },
};
