export const studentAiCopy = {
  en: {
    quick:'⚡ QuickMatch',quickHint:'Find one job based on your work information and available shifts.',find:'Find a job',finding:'Finding a job…',noJob:'No suitable active job is available right now.',needsProfile:'Add availability, skills, experience or preferences in Profile to get a personal recommendation.',missingAvailability:'Add your availability to improve QuickMatch. Confirm the shift before applying.',missingSkills:'Add work skills or experience for more useful explanations.',why:'Why this job',skip:'Skip',interested:'Interested',confirmTitle:'Apply for this job?',confirmBody:'Review the details and confirm before submitting your application.',viewJob:'View job details',confirmApply:'Confirm application',applied:'Application submitted.',skipFailed:'Could not skip this job. Please try again.',retry:'Try again',
    radar:'Job Radar',radarHint:'Relevant jobs from your saved work information. Refreshed when you open Home.',refresh:'Refresh Radar',noRadar:'No new relevant jobs yet.',dismiss:'Dismiss',radarFailed:'Could not update Job Radar.',new:'New',seen:'Seen',
    discovery:'Opportunity Discovery',discoveryHint:'See other job types your stated experience may support. Suggestions do not change your profile.',discover:'Discover opportunities',noExperience:'Add work experience in Profile to discover more job types.',noCategories:'No relevant active job categories are available now.',possibleSkills:'Possible skills from your experience',possibleJobs:'Job types to explore',viewJobs:'View jobs',
    preferences:'Job preferences',preferenceHint:'Optional filters for recommendations. Minimum wage is compared only with jobs using the same wage unit.',category:'Preferred category',area:'Preferred area or location',minimumWage:'Minimum wage',wageType:'Wage unit',all:'Any category',save:'Save preferences',saved:'Preferences saved.',
    unauthorized:'Sign in as a verified Student.',forbidden:'A verified Student account is required.',invalidRequest:'Check the entered information.',notConfigured:'AI is not configured on the server.',rateLimited:'AI limit reached. Please try again later.',providerUnavailable:'AI is temporarily unavailable. Please retry later.',invalidOutput:'AI returned an unusable result. Please retry.',unavailable:'Could not load recommendations. Check your connection and try again.',tooManyRecords:'Too many records to analyze safely. Please narrow your data.',refused:'AI could not analyze this information.',
  },
  th: {
    quick:'⚡ QuickMatch',quickHint:'หางานหนึ่งงานจากข้อมูลการทำงานและเวลาว่างของคุณ',find:'หางานให้ฉัน',finding:'กำลังหางาน…',noJob:'ยังไม่มีงานที่เปิดรับและตรงเงื่อนไขในขณะนี้',needsProfile:'เพิ่มเวลาว่าง ทักษะ ประสบการณ์ หรือความต้องการในโปรไฟล์ก่อน เพื่อให้แนะนำงานเฉพาะคุณ',missingAvailability:'เพิ่มเวลาว่างเพื่อให้ QuickMatch แม่นยำขึ้น และยืนยันเวลากะก่อนสมัคร',missingSkills:'เพิ่มทักษะหรือประสบการณ์เพื่อให้เหตุผลประกอบชัดขึ้น',why:'เหตุผลที่แนะนำ',skip:'ข้าม',interested:'สนใจ',confirmTitle:'ต้องการสมัครงานนี้หรือไม่',confirmBody:'ดูรายละเอียดและยืนยันก่อนส่งใบสมัครจริง',viewJob:'ดูรายละเอียดงาน',confirmApply:'ยืนยันสมัครงาน',applied:'ส่งใบสมัครแล้ว',skipFailed:'ข้ามงานไม่สำเร็จ กรุณาลองใหม่',retry:'ลองอีกครั้ง',
    radar:'Job Radar',radarHint:'งานที่เกี่ยวข้องกับข้อมูลของคุณ จะอัปเดตเมื่อเปิดหน้าแรก',refresh:'อัปเดต Radar',noRadar:'ยังไม่มีงานใหม่ที่เกี่ยวข้อง',dismiss:'ซ่อน',radarFailed:'อัปเดต Job Radar ไม่สำเร็จ',new:'ใหม่',seen:'ดูแล้ว',
    discovery:'Opportunity Discovery',discoveryHint:'ค้นพบงานประเภทอื่นจากประสบการณ์ที่คุณระบุ ข้อเสนอแนะไม่แก้โปรไฟล์ของคุณ',discover:'ค้นหาโอกาสงาน',noExperience:'เพิ่มประสบการณ์ในโปรไฟล์ก่อน เพื่อค้นพบงานประเภทอื่น',noCategories:'ตอนนี้ยังไม่มีหมวดงานที่เปิดรับและเกี่ยวข้อง',possibleSkills:'ทักษะที่อาจมีจากประสบการณ์',possibleJobs:'ประเภทงานที่น่าลอง',viewJobs:'ดูงาน',
    preferences:'ความต้องการเกี่ยวกับงาน',preferenceHint:'ตัวกรองสำหรับงานแนะนำ ค่าจ้างขั้นต่ำจะเทียบเฉพาะงานที่ใช้หน่วยเดียวกัน',category:'หมวดงานที่สนใจ',area:'พื้นที่หรือสถานที่ที่สนใจ',minimumWage:'ค่าจ้างขั้นต่ำ',wageType:'หน่วยค่าจ้าง',all:'ทุกหมวด',save:'บันทึกความต้องการ',saved:'บันทึกแล้ว',
    unauthorized:'กรุณาเข้าสู่ระบบนิสิตที่ยืนยันแล้ว',forbidden:'ต้องใช้บัญชีนิสิตที่ยืนยันแล้ว',invalidRequest:'กรุณาตรวจสอบข้อมูลที่กรอก',notConfigured:'ยังไม่ได้ตั้งค่า AI ที่เซิร์ฟเวอร์',rateLimited:'ใช้ AI ครบจำนวนที่กำหนด กรุณาลองภายหลัง',providerUnavailable:'AI ไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่',invalidOutput:'ผลจาก AI ไม่ถูกต้อง กรุณาลองใหม่',unavailable:'โหลดงานแนะนำไม่สำเร็จ ตรวจสอบการเชื่อมต่อแล้วลองใหม่',tooManyRecords:'มีข้อมูลมากเกินกว่าจะวิเคราะห์ได้อย่างปลอดภัย',refused:'AI ไม่สามารถวิเคราะห์ข้อมูลนี้ได้',
  },
};
