export const aiCopy = {
  en: {
    insight: 'AI Candidate Insight', analyze: 'Analyze with AI', regenerate: 'Analyze again', loading: 'Analyzing…',
    summary: 'Summary', strengths: 'Strengths', gaps: 'Potential gaps / missing information', questions: 'Suggested interview questions',
    note: 'AI assists evaluation only. The Employer makes the final hiring decision. Verify all claims with the student.',
    privacy: 'Only job requirements, work skills, experience and availability checks are sent to the AI provider. Names and contact details are not sent.',
    emptyInsight: 'Choose Analyze with AI to review the available work information. Analysis does not change the application status.',
    noEvidence: 'No supported information provided.', success: 'Analysis complete.', available: 'Declared availability covers this shift; no overlapping accepted job found.',
    conflict: 'Schedule conflict: declared availability does not cover the shift, or an accepted job overlaps.', unknown: 'Availability or an accepted job’s shift is missing or unclear.',
    date: 'Available date (YYYY-MM-DD, Bangkok)', start: 'Available from (HH:mm)', end: 'Available until (HH:mm; earlier time means next day)',
    unavailable: 'Could not complete the request. Check your connection and the deployed AI function.',
    workContext: 'Work skills and availability', skills: 'Job-related skills', experience: 'Relevant work experience (optional)',
    workHelp: 'Add only job-related information. Your availability helps QuickMatch and Job Radar find suitable jobs. Employers you apply to can see work-related AI insights.',
    availability: 'Saved available windows', remove: 'Remove window', removed: 'Available window removed.', save: 'Save work information and availability', saved: 'Work information and availability saved.',
    savedWorkOnly: 'Work information saved. No available window was entered yet.',
    noWindows: 'No upcoming available windows saved yet. Enter a date and start/end time, then press Save below. Past windows are hidden.',
    windowExample: 'Choose an upcoming date, for example 18:00 to 22:00 (Bangkok time). For an overnight window, enter an end time earlier than the start time.',
    invalidDate: 'Enter a real upcoming date in YYYY-MM-DD format.',
    invalidTime: 'Enter both times in 24-hour HH:mm format, for example 18:00 and 22:00.',
    pastWindow: 'This window has already ended. Choose a future date or time.',
    availabilitySaveFailed: 'Could not confirm that this window was saved. Please check your connection and try again.',
    unauthorized: 'Please sign in again.', forbidden: 'A verified account with the correct role is required.', notFound: 'Job or application not found, or you do not own it.',
    notConfigured: 'AI is not configured yet. Ask the project administrator to configure the server-side AI key and model.',
    invalidShift: 'Start and end times must differ, and the available window must be no longer than 24 hours.',
    invalidRequest: 'Please check the submitted information.', rateLimited: 'AI request limit reached. Please try again later.',
    tooManyCandidates: 'This request exceeds the current safe analysis limit. Review applicants manually.',
    providerUnavailable: 'The AI provider is unavailable. Please try again later.', invalidOutput: 'AI returned an unusable response. Please try again.',
    refused: 'AI could not analyze this information. Review the applicant manually.', realAccountRequired: 'AI requires a real signed-in account and saved job; demo data is not analyzed.',
    invalidWork: 'Skills must be at most 1,000 characters and experience at most 3,000 characters.', loadingData: 'Loading work information…',
  },
  th: {
    insight: 'AI วิเคราะห์ข้อมูลผู้สมัคร', analyze: 'วิเคราะห์ด้วย AI', regenerate: 'วิเคราะห์อีกครั้ง', loading: 'กำลังวิเคราะห์…',
    summary: 'สรุปข้อมูล', strengths: 'จุดเด่นที่มีข้อมูลรองรับ', gaps: 'สิ่งที่ยังไม่ชัดเจน / ข้อมูลที่ขาด', questions: 'คำถามสำหรับสัมภาษณ์',
    verifyAvailability: 'ยังไม่มีข้อมูลเวลาว่างที่ยืนยันได้ กรุณาถามผู้สมัครว่าว่างตรงวันและเวลากะของงานหรือไม่ และให้เพิ่มช่วงเวลาว่างในโปรไฟล์',
    verifyMissing: 'รายละเอียดบางส่วนยังไม่ชัดเจน กรุณาถามผู้สมัครเกี่ยวกับประสบการณ์และทักษะที่งานนี้ต้องใช้',
    verifyQuestion: 'คุณมีประสบการณ์และเวลาว่างตรงตามข้อกำหนดของงานนี้หรือไม่',
    translationFallback: 'AI ส่งข้อความภาษาอื่นกลับมา กรุณาตรวจข้อมูลผู้สมัครและข้อกำหนดงานโดยตรง แล้วลองวิเคราะห์อีกครั้ง',
    note: 'AI ช่วยประกอบการพิจารณาเท่านั้น นายจ้างเป็นผู้ตัดสินใจจ้างงาน กรุณาตรวจสอบข้อมูลกับนิสิตอีกครั้ง',
    privacy: 'ส่งเฉพาะข้อกำหนดงาน ทักษะ ประสบการณ์ และผลตรวจเวลาว่างให้ผู้ให้บริการ AI ไม่ส่งชื่อหรือข้อมูลติดต่อ',
    emptyInsight: 'กดวิเคราะห์ด้วย AI เพื่อสรุปข้อมูลเกี่ยวกับงาน การวิเคราะห์จะไม่เปลี่ยนสถานะใบสมัคร',
    noEvidence: 'ยังไม่มีข้อมูลที่รองรับ', success: 'วิเคราะห์เสร็จแล้ว', available: 'เวลาว่างที่แจ้งครอบคลุมกะนี้ และไม่พบงานที่รับแล้วซ้อนกัน',
    conflict: 'เวลาขัดกัน: เวลาว่างไม่ครอบคลุมกะ หรือมีงานที่รับแล้วซ้อนกัน', unknown: 'ยังไม่มีเวลาว่าง หรือเวลากะของงานที่รับแล้วยังไม่ชัดเจน',
    date: 'วันที่สะดวก (ปี-เดือน-วัน เวลาไทย)', start: 'สะดวกตั้งแต่ (HH:mm)', end: 'สะดวกถึง (HH:mm; ถ้าเร็วกว่าคือวันถัดไป)',
    unavailable: 'ดำเนินการไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อและฟังก์ชัน AI',
    workContext: 'ทักษะและเวลาว่างสำหรับทำงาน', skills: 'ทักษะที่เกี่ยวข้องกับงาน', experience: 'ประสบการณ์ทำงาน (ไม่บังคับ)',
    workHelp: 'กรอกเฉพาะข้อมูลที่เกี่ยวกับงาน เวลาว่างช่วยให้ QuickMatch และ Job Radar หางานที่เหมาะขึ้น นายจ้างที่คุณสมัครสามารถดูข้อมูลการทำงานผ่าน AI ได้',
    availability: 'ช่วงเวลาว่างที่บันทึกไว้', remove: 'ลบช่วงเวลา', removed: 'ลบช่วงเวลาว่างแล้ว', save: 'บันทึกข้อมูลการทำงานและเวลาว่าง', saved: 'บันทึกข้อมูลการทำงานและเวลาว่างแล้ว',
    savedWorkOnly: 'บันทึกข้อมูลการทำงานแล้ว แต่ยังไม่ได้กรอกช่วงเวลาว่าง',
    noWindows: 'ยังไม่มีช่วงเวลาว่างที่กำลังจะมาถึง กรอกวันที่ เวลาเริ่ม และเวลาสิ้นสุด แล้วกดบันทึกด้านล่าง เวลาที่ผ่านไปแล้วจะไม่แสดง',
    windowExample: 'เลือกวันที่ในอนาคต เช่น เวลา 18:00 ถึง 22:00 (เวลาไทย) ถ้าเลิกงานหลังเที่ยงคืน ให้กรอกเวลาสิ้นสุดที่น้อยกว่าเวลาเริ่ม',
    invalidDate: 'กรุณากรอกวันที่ในอนาคตตามรูปแบบ ปี-เดือน-วัน (YYYY-MM-DD)',
    invalidTime: 'กรุณากรอกเวลาเริ่มและสิ้นสุดแบบ 24 ชั่วโมง เช่น 18:00 และ 22:00',
    pastWindow: 'ช่วงเวลานี้สิ้นสุดไปแล้ว กรุณาเลือกวันหรือเวลาที่ยังมาไม่ถึง',
    availabilitySaveFailed: 'ยังยืนยันไม่ได้ว่าบันทึกช่วงเวลานี้สำเร็จ กรุณาตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง',
    unauthorized: 'กรุณาเข้าสู่ระบบใหม่อีกครั้ง', forbidden: 'ต้องใช้บัญชีที่ยืนยันแล้วและมีบทบาทถูกต้อง', notFound: 'ไม่พบงานหรือใบสมัคร หรือคุณไม่ใช่เจ้าของงาน',
    notConfigured: 'ยังไม่ได้ตั้งค่า AI กรุณาให้ผู้ดูแลตั้งค่า API key และโมเดลในฝั่งเซิร์ฟเวอร์',
    invalidShift: 'เวลาเริ่มและสิ้นสุดต้องไม่ตรงกัน และช่วงเวลาต้องไม่เกิน 24 ชั่วโมง',
    invalidRequest: 'กรุณาตรวจสอบข้อมูลที่กรอก', rateLimited: 'ใช้ AI ครบจำนวนที่กำหนดแล้ว กรุณาลองใหม่ภายหลัง',
    tooManyCandidates: 'ข้อมูลเกินขนาดที่รองรับอย่างปลอดภัยในรุ่นนี้ กรุณาตรวจผู้สมัครด้วยตนเอง',
    providerUnavailable: 'ผู้ให้บริการ AI ไม่พร้อมใช้งาน กรุณาลองอีกครั้ง', invalidOutput: 'ผล AI ไม่ถูกต้อง กรุณาลองอีกครั้ง',
    refused: 'AI ไม่สามารถวิเคราะห์ข้อมูลนี้ได้ กรุณาตรวจผู้สมัครด้วยตนเอง', realAccountRequired: 'AI ใช้ได้กับบัญชีจริงและงานที่บันทึกแล้วเท่านั้น ไม่วิเคราะห์ข้อมูลสาธิต',
    invalidWork: 'ทักษะต้องไม่เกิน 1,000 ตัวอักษร และประสบการณ์ไม่เกิน 3,000 ตัวอักษร', loadingData: 'กำลังโหลดข้อมูลการทำงาน…',
  },
};
