export const aiCopy = {
  en: {
    insight: 'AI Candidate Insight', analyze: 'Analyze with AI', regenerate: 'Analyze again', loading: 'Analyzing…',
    summary: 'Summary', strengths: 'Strengths', gaps: 'Potential gaps / missing information', questions: 'Suggested interview questions',
    note: 'AI assists evaluation only. The Employer makes the final hiring decision. Verify all claims with the student.',
    privacy: 'Only job requirements, work skills, experience and availability checks are sent to the AI provider. Names and contact details are not sent.',
    emptyInsight: 'Choose Analyze with AI to review the available work information. Analysis does not change the application status.',
    noEvidence: 'No supported information provided.', success: 'Analysis complete.', available: 'Declared availability covers this shift; no overlapping accepted job found.',
    conflict: 'Schedule conflict: declared availability does not cover the shift, or an accepted job overlaps.', unknown: 'Availability or an accepted job’s shift is missing or unclear.',
    replacement: 'AI Emergency Replacement', find: 'Find Emergency Replacement', pool: 'Reviews pending applicants to this job only, in application order. No AI ranking. Contact and confirm before hiring.',
    date: 'Shift date (YYYY-MM-DD, Bangkok)', start: 'Start time (HH:mm)', end: 'End time (HH:mm; earlier time means next day)',
    noCandidates: 'No eligible applicants found for this shift.', reasons: 'Why this person may be suitable', warnings: 'Confirm before contacting', view: 'View applicant / contact',
    missingAvailability: 'Missing availability', unavailable: 'Could not complete the request. Check your connection and the deployed AI function.',
    unavailableCount: 'Not available for the full shift', overlapping: 'Overlapping accepted job', unknownCommitment: 'Unclear existing work schedule',
    confirmShift: 'Availability is student-declared. Accepted applications are treated as commitments; external work is not visible.',
    workContext: 'Work skills and availability', skills: 'Job-related skills', experience: 'Relevant work experience (optional)',
    workHelp: 'Include work information only, not sensitive personal details. Employers you apply to can use it for AI insights. Available windows are used to check potential replacement shifts.',
    availability: 'Available windows', addWindow: 'Add available window', remove: 'Remove window', save: 'Save work information', saved: 'Saved.',
    noWindows: 'No availability recorded. You will not appear in emergency replacement results until you add a matching window.',
    unauthorized: 'Sign in with a real Employer account.', forbidden: 'A verified Employer account is required.', notFound: 'Job or application not found, or you do not own it.',
    notConfigured: 'AI is not configured yet. Ask the project administrator to configure the server-side AI key and model.',
    invalidShift: 'Enter a valid shift of up to 24 hours, ending in the future and starting within 31 days.',
    invalidRequest: 'Please check the submitted information.', rateLimited: 'AI request limit reached. Please try again later.',
    tooManyCandidates: 'This request exceeds the current safe analysis limit. Review applicants manually.',
    providerUnavailable: 'The AI provider is unavailable. Please try again later.', invalidOutput: 'AI returned an unusable response. Please try again.',
    refused: 'AI could not analyze this information. Review the applicant manually.', realAccountRequired: 'AI requires a real signed-in account and saved job; demo data is not analyzed.',
    invalidWork: 'Skills must be at most 1,000 characters and experience at most 3,000 characters.', loadingData: 'Loading work information…',
  },
  th: {
    insight: 'AI วิเคราะห์ข้อมูลผู้สมัคร', analyze: 'วิเคราะห์ด้วย AI', regenerate: 'วิเคราะห์อีกครั้ง', loading: 'กำลังวิเคราะห์…',
    summary: 'สรุปข้อมูล', strengths: 'จุดเด่นที่มีข้อมูลรองรับ', gaps: 'สิ่งที่ยังไม่ชัดเจน / ข้อมูลที่ขาด', questions: 'คำถามสำหรับสัมภาษณ์',
    note: 'AI ช่วยประกอบการพิจารณาเท่านั้น นายจ้างเป็นผู้ตัดสินใจจ้างงาน กรุณาตรวจสอบข้อมูลกับนิสิตอีกครั้ง',
    privacy: 'ส่งเฉพาะข้อกำหนดงาน ทักษะ ประสบการณ์ และผลตรวจเวลาว่างให้ผู้ให้บริการ AI ไม่ส่งชื่อหรือข้อมูลติดต่อ',
    emptyInsight: 'กดวิเคราะห์ด้วย AI เพื่อสรุปข้อมูลเกี่ยวกับงาน การวิเคราะห์จะไม่เปลี่ยนสถานะใบสมัคร',
    noEvidence: 'ยังไม่มีข้อมูลที่รองรับ', success: 'วิเคราะห์เสร็จแล้ว', available: 'เวลาว่างที่แจ้งครอบคลุมกะนี้ และไม่พบงานที่รับแล้วซ้อนกัน',
    conflict: 'เวลาขัดกัน: เวลาว่างไม่ครอบคลุมกะ หรือมีงานที่รับแล้วซ้อนกัน', unknown: 'ยังไม่มีเวลาว่าง หรือเวลากะของงานที่รับแล้วยังไม่ชัดเจน',
    replacement: 'AI หาคนทดแทนฉุกเฉิน', find: 'หาคนทดแทนฉุกเฉิน', pool: 'ตรวจเฉพาะผู้สมัครที่รอพิจารณาของงานนี้ เรียงตามเวลาสมัคร ไม่ใช่อันดับจาก AI ต้องติดต่อยืนยันก่อนจ้าง',
    date: 'วันที่ทำงาน (YYYY-MM-DD เวลาไทย)', start: 'เวลาเริ่ม (HH:mm)', end: 'เวลาสิ้นสุด (HH:mm; ถ้าเร็วกว่าคือวันถัดไป)',
    noCandidates: 'ไม่พบผู้สมัครที่ผ่านเงื่อนไขเวลาสำหรับกะนี้', reasons: 'ข้อมูลที่อาจเหมาะกับงาน', warnings: 'สิ่งที่ควรยืนยัน', view: 'ดูผู้สมัคร / ช่องทางติดต่อ',
    missingAvailability: 'ไม่มีข้อมูลเวลาว่าง', unavailable: 'ดำเนินการไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อและการ deploy ฟังก์ชัน AI',
    unavailableCount: 'ว่างไม่ครบกะ', overlapping: 'มีงานที่รับแล้วซ้อนกัน', unknownCommitment: 'เวลางานที่รับแล้วยังไม่ชัดเจน',
    confirmShift: 'เวลาว่างเป็นข้อมูลที่นิสิตแจ้ง งานที่รับแล้วถือเป็นเวลาติดงาน ระบบไม่ทราบงานภายนอกแอป',
    workContext: 'ทักษะและเวลาว่างสำหรับทำงาน', skills: 'ทักษะที่เกี่ยวข้องกับงาน', experience: 'ประสบการณ์ทำงาน (ไม่บังคับ)',
    workHelp: 'กรอกเฉพาะข้อมูลการทำงาน ไม่ใส่ข้อมูลส่วนบุคคลที่อ่อนไหว นายจ้างที่คุณสมัครงานสามารถใช้ประกอบการวิเคราะห์ด้วย AI และตรวจเวลาว่างเพื่อหาคนทดแทนได้',
    availability: 'ช่วงเวลาที่สะดวก', addWindow: 'เพิ่มช่วงเวลาว่าง', remove: 'ลบช่วงเวลา', save: 'บันทึกข้อมูลการทำงาน', saved: 'บันทึกแล้ว',
    noWindows: 'ยังไม่มีเวลาว่าง คุณจะไม่ปรากฏในผลหาคนทดแทนจนกว่าจะเพิ่มเวลาที่ตรงกับกะ',
    unauthorized: 'กรุณาเข้าสู่ระบบด้วยบัญชีนายจ้างจริง', forbidden: 'ต้องใช้บัญชีนายจ้างที่ยืนยันแล้ว', notFound: 'ไม่พบงานหรือใบสมัคร หรือคุณไม่ใช่เจ้าของงาน',
    notConfigured: 'ยังไม่ได้ตั้งค่า AI กรุณาให้ผู้ดูแลตั้งค่า API key และโมเดลในฝั่งเซิร์ฟเวอร์',
    invalidShift: 'กรอกกะที่ถูกต้องไม่เกิน 24 ชั่วโมง ยังไม่สิ้นสุด และเริ่มภายใน 31 วัน',
    invalidRequest: 'กรุณาตรวจสอบข้อมูลที่กรอก', rateLimited: 'ใช้ AI ครบจำนวนที่กำหนดแล้ว กรุณาลองใหม่ภายหลัง',
    tooManyCandidates: 'ข้อมูลเกินขนาดที่รองรับอย่างปลอดภัยในรุ่นนี้ กรุณาตรวจผู้สมัครด้วยตนเอง',
    providerUnavailable: 'ผู้ให้บริการ AI ไม่พร้อมใช้งาน กรุณาลองอีกครั้ง', invalidOutput: 'ผล AI ไม่ถูกต้อง กรุณาลองอีกครั้ง',
    refused: 'AI ไม่สามารถวิเคราะห์ข้อมูลนี้ได้ กรุณาตรวจผู้สมัครด้วยตนเอง', realAccountRequired: 'AI ใช้ได้กับบัญชีจริงและงานที่บันทึกแล้วเท่านั้น ไม่วิเคราะห์ข้อมูลสาธิต',
    invalidWork: 'ทักษะต้องไม่เกิน 1,000 ตัวอักษร และประสบการณ์ไม่เกิน 3,000 ตัวอักษร', loadingData: 'กำลังโหลดข้อมูลการทำงาน…',
  },
};
